version: '4'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperless
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      custom_net:
        ipv4_address: 10.5.0.50

  app:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .src:/app/src
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperless
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
       - JAVA_OPTS=-Xmx512m
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

  nginx:
    image: nginx:1-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      custom_net:
        ipv4_address: 10.5.0.2

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres_data: